#### １. 向上取整  ```np.ceil``` 输出的为浮点型数组
```python
>>> a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
>>> np.ceil(a)
array([-1., -1., -0.,  1.,  2.,  2.,  2.])
```
#### 2.向下取整 ```np.float``` 输出的为浮点型数组
```python
>>> a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
>>> np.floor(a)
array([-2., -2., -1.,  0.,  1.,  1.,  2.])
```
#### 3.数组取值, 对一个数组取值, 可以只取给定的值, 其它轴的值可以忽略, 简单方便
```python 
>>> a = np.arange(3*2*3).reshape(3,2,3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],
       [[ 6,  7,  8],
        [ 9, 10, 11]],
       [[12, 13, 14],
        [15, 16, 17]]])
>>> a[...,1]
array([[ 1,  4],
       [ 7, 10],
       [13, 16]])
```
### 4.函数的拼接
```python
help(np.r_[])
#examples:
>>> import numpy as np
>>> a = np.array([[0, 1, 2], [3, 4, 5]])
>>> np.r_['-1', a, a] #concatenate along last axis
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])
```
#### 5.计算阶乘
```python 
np.cumprod(r) #计算阶乘
#examples：
>>>r = np.arange(1, 10)
>>>np.cumprod(r)
array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])
```
#### 6.求方阵的行列式```np.linalg.det```
#### 7.SymPy是Python的数学符号计算库，用它可以进行数学公式的符号推导
```python
from sympy import *
x = Symbol('x')
y = Symbol('')
a = np.array([[x, y, 1], [1,2,3]])
```
#### 8.交换两个数轴```np.swapaxis```
```python
>>> x = np.array([[1,2,3]])
>>> np.swapaxes(x,0,1)
array([[1],
       [2],
       [3]])
>>> x = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
>>> x
array([[[0, 1],
        [2, 3]],
       [[4, 5],
        [6, 7]]])
>>> np.swapaxes(x,0,2)
array([[[0, 4],
        [2, 6]],
       [[1, 5],
        [3, 7]]])
```
#### 9.python中计时工具timeit模块的基本用法
timeit(stmt='pass', setup='pass', timer=<defaulttimer>, number=1000000)
返回：
$\quad$  返回执行stmt这段代码number遍所用的时间，单位为秒，float型
 参数：
$\quad$  stmt：要执行的那段代码
$\quad$  setup：执行代码的准备工作，不计入时间，一般是import之类的
$\quad$  timer：这个在win32下是time.clock()，linux下是time.time()，默认的，不用管
$\quad$  number：要执行stmt多少遍
```python
In [1]: from timeit import timeit as timeit  
      
In [2]: timeit('x=1')  
Out[2]: 0.03820111778328037  
      
In [3]: timeit('x=map(lambda x:x*10,range(32))')  
Out[3]: 8.05639690328919  
```

为了使timeit模块可以测量我们自己的函数，可以在setup参数中通过import语句导入：
```python
def test():
     """Stupid test function"""
    L = [i for i in range(100)]
if __name__ == '__main__':
    import timeit
    print(timeit.timeit("test()", setup="from __main__ import test"))
```

测试爱因斯坦求和速度
```python
def test(p, NE, ldof):
     point = np.random.rand(p, NE, ldof)
     ws = np.random.rand(p+1)
     nm = np.random.rand(NE, 2)
     val = np.einsum('jk, ijmk->ijm', nm, gphi)
     val = np.einsum('i, ijm->ijm', ws, val)
     
if __name__ == '__main__':
     import timeit
     print(timeit.timeit('test(2, 5, 6)', setup="from __main__ import test"))
7.794546781000463


def test(p, NE, ldof):
     point = np.random.rand(p, NE, ldof)
     ws = np.random.rand(p+1)
     nm = np.random.rand(NE, 2)
     val = np.einsum('i, jk, ijmk->ijm', ws, nm, gphi)

 if __name__ == '__main__':
     import timeit
     print(timeit.timeit('test(2, 5, 6)', setup="from __main__ import 
test"))
6.954014050999831
```

#### 2.一些函数的拼接:
```python
help(np.r_[])
#examples:
import numpy as np
a = np.array([[0, 1, 2], [3, 4, 5]])
np.r_['-1', a, a] #concatenate along last axis
# 结果为
array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])
```
可以通过字符串的限制拼接的形状.
```python 
np.cumprod(r) #计算阶乘
＃examples：
r = np.arange(1, 10)
np.cumprod(r)
```