## 爱因斯坦求和示例解释

### 例1

In [79]:
import numpy as np

In [80]:
A = np.array([0,1,2])
A

array([0, 1, 2])

In [81]:
B = np.array([[0,1,2,3],
              [4,5,6,7],
              [8,9,10,11]])
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
C = np.einsum('i,ij->i',A,B)

In [83]:
C

array([ 0, 22, 76])

基于对爱因斯坦求和的理解：

我们将这个函数翻译等价符号 $(A_iB_{ij})$

$i = 1:$
$$
A_1B_{11}+A_1B_{12}+A_1B_{13}+A_1B_{14}
$$

$i =2:$
$$
A_2B_{21}+A_2B_{22}+A_2B_{23}+A_2B_{24}
$$

$i =3:$
$$
A_3B_{31}+A_3B_{32}+A_3B_{33}+A_3B_{34}
$$

保持 $i$ 轴方便的维数不变.

$\text{np.einsum('i,ij->i',A,B)}$ 这个函数的意思：

1. A 的形状是 shape(i,), B 的形状是 shape(i,j);
2. A 乘 B 的每一列;
3. 沿着 j 轴的方向求和, 最终保持 i 轴的形状不变,

问题: 如果你写了  np.einsum('i,ij->ij',A,B), 那么就没有求和了, 因为没有下标被省略

In [84]:
C1 = np.einsum('i,ij->ij',A,B)
C1

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

### example1:

没有省略的下标，所以没有求和, 只需要 A 乘 B 的列即可

In [85]:
C1 = np.einsum('i,ij->ij',A,B)
C1

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [86]:
C2 = (A[:,None]*B)
C2

array([[ 0,  0,  0,  0],
       [ 4,  5,  6,  7],
       [16, 18, 20, 22]])

In [87]:
(np.einsum('i,ij->ij',A,B) == (A[:,None]*B)).all()

True

### example2:

同样的例子 A 乘以 B 的列求和, 然后输出求和的列.

In [88]:
C = np.einsum('i,ij->i',A,B)
C

array([ 0, 22, 76])

In [89]:
C3 = (A[:,None]*B).sum(axis =1)
C3

array([ 0, 22, 76])

In [90]:
(np.einsum('i,ij->i',A,B) == (A[:,None]*B).sum(axis =1)).all()

True

### example3:

In [91]:
C4 = np.einsum('i,ij->j',A,B)
C4

array([20, 23, 26, 29])

In [92]:
C5 = (A[:,None]*B).sum(axis =0)
C5

array([20, 23, 26, 29])

In [93]:
C6 = (np.einsum('i,ij->j',A,B) == (A[:,None]*B).sum(axis =0)).all()
C6 

True

### example4:

In [94]:
np.einsum('i,ij->',A,B)

98

### example5:

In [95]:
np.einsum('i,jk',A,B)

array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]]])

In [96]:
np.einsum('i,jk',A,B).shape

(3, 3, 4)

## 第二部分

一个稍微大一点例子

In [97]:
A1= np.array([[1,1,1],
               [2,2,2],
               [5,5,5]])
B1 = np.array([[0,1,0],
               [1,1,0],
               [1,1,1]])

In [98]:
np.einsum('ij,jk->ik',A1,B1)

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

我们可以看到标签 j 是重复的,　这意味着我们将 A 的行和 B 的列相乘, 此外 标签 j　不在输出中, 我们要对这些结果求和, 保持 i,k 得到一个二维数组.

In [99]:
np.einsum('ij,jk->ijk',A1,B1)

array([[[0, 1, 0],
        [1, 1, 0],
        [1, 1, 1]],

       [[0, 2, 0],
        [2, 2, 0],
        [2, 2, 2]],

       [[0, 5, 0],
        [5, 5, 0],
        [5, 5, 5]]])

### 一些练习

In [100]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
B = np.arange(5,15)
B

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

数组 A 求和

In [102]:
np.einsum('i->',A)

45

元素乘法

In [103]:
np.einsum('i,i->i',A,B)

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [104]:
np.inner(A,B)

510

In [105]:
np.dot(A,B)

510

In [106]:
np.einsum('i,i->',A,B)

510

In [107]:
np.einsum('i,j->ij',A,B)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  5,   6,   7,   8,   9,  10,  11,  12,  13,  14],
       [ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28],
       [ 15,  18,  21,  24,  27,  30,  33,  36,  39,  42],
       [ 20,  24,  28,  32,  36,  40,  44,  48,  52,  56],
       [ 25,  30,  35,  40,  45,  50,  55,  60,  65,  70],
       [ 30,  36,  42,  48,  54,  60,  66,  72,  78,  84],
       [ 35,  42,  49,  56,  63,  70,  77,  84,  91,  98],
       [ 40,  48,  56,  64,  72,  80,  88,  96, 104, 112],
       [ 45,  54,  63,  72,  81,  90,  99, 108, 117, 126]])

2D 数组 C 和 D

In [108]:
A = np.arange(6).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [109]:
B = np.arange(12).reshape(3,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

计算一个(2,3) 和(3,4) 的得到(4,2) 数组, 

In [110]:
C = np.einsum('ij,jk->ki',A,B)

In [111]:
C

array([[20, 56],
       [23, 68],
       [26, 80],
       [29, 92]])

In [112]:
np.dot(A,B).T

array([[20, 56],
       [23, 68],
       [26, 80],
       [29, 92]])

In [113]:
np.einsum('ij,jk->ijk',A,B)

array([[[ 0,  0,  0,  0],
        [ 4,  5,  6,  7],
        [16, 18, 20, 22]],

       [[ 0,  3,  6,  9],
        [16, 20, 24, 28],
        [40, 45, 50, 55]]])

In [114]:
A[:,:,None]*B[None,:,:]

array([[[ 0,  0,  0,  0],
        [ 4,  5,  6,  7],
        [16, 18, 20, 22]],

       [[ 0,  3,  6,  9],
        [16, 20, 24, 28],
        [40, 45, 50, 55]]])